import type { MediaAsset } from '@/types/content';

/**
 * Curated mock MediaAsset items for Content Builder Admin UI preparation.
 * All properties strictly conform to canonical MediaAsset in src/types/content/content.ts.
 */
export const MOCK_MEDIA_LIBRARY: MediaAsset[] = [
  {
    id: 'media-oria-interior-01',
    title: 'Không gian sảnh chính Oria Spa & Lounge',
    type: 'image',
    url: '/images/showcase/1.webp',
    source: 'supabase',
    width: 1920,
    height: 1080,
    mime_type: 'image/webp',
    file_size: 1420000,
    alt_i18n: {
      vi: 'Sảnh chính Oria Spa với ánh sáng ấm cúng',
      en: 'Main lounge of Oria Spa with warm ambient lighting',
      cn: 'Oria水疗中心主休息室',
      jp: 'Oriaスパのメインラウンジ',
      kr: 'Oria 스파 메인 라운지',
    },
    default_focal_point: { x: 50, y: 50 },
    created_at: '2026-03-01T10:00:00.000Z',
    updated_at: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'media-oria-massage-02',
    title: 'Liệu trình thư giãn thảo mộc cổ truyền',
    type: 'image',
    url: '/images/showcase/2.webp',
    source: 'supabase',
    width: 1600,
    height: 1200,
    mime_type: 'image/webp',
    file_size: 1180000,
    alt_i18n: {
      vi: 'Chuyên viên thực hiện liệu trình mát-xa cổ truyền',
      en: 'Therapist performing traditional herbal massage',
      cn: '理疗师进行传统草药按摩',
      jp: '伝統的なハーブマッサージを行うセラピスト',
      kr: '전통 허브 마사지를 진행하는 테라피스트',
    },
    default_focal_point: { x: 45, y: 40 },
    created_at: '2026-03-02T11:30:00.000Z',
    updated_at: '2026-03-02T11:30:00.000Z',
  },
  {
    id: 'media-oria-oil-03',
    title: 'Bộ tinh dầu organic Oria Farm',
    type: 'image',
    url: '/images/showcase/3.webp',
    source: 'supabase',
    width: 1200,
    height: 1200,
    mime_type: 'image/webp',
    file_size: 850000,
    alt_i18n: {
      vi: 'Lọ tinh dầu tự nhiên chiết xuất từ nông trại Oria',
      en: 'Natural essential oil bottles extracted from Oria Farm',
      cn: 'Oria农场天然精油瓶',
      jp: 'Oriaファームで抽出された天然エッセンシャルオイル',
      kr: 'Oria 팜에서 추출한 천연 에센셜 오일 병',
    },
    default_focal_point: { x: 50, y: 60 },
    created_at: '2026-03-03T09:15:00.000Z',
    updated_at: '2026-03-03T09:15:00.000Z',
  },
  {
    id: 'media-oria-tea-04',
    title: 'Trà thảo mộc chào đón & bánh dưỡng sinh',
    type: 'image',
    url: '/images/showcase/4.webp',
    source: 'supabase',
    width: 1920,
    height: 1280,
    mime_type: 'image/webp',
    file_size: 1620000,
    alt_i18n: {
      vi: 'Bộ ấm trà gốm mộc và bánh hạt dinh dưỡng',
      en: 'Ceramic herbal tea set and nourishing pastries',
      cn: '陶瓷草药茶具与养生糕点',
      jp: '陶器のハーブティーセットと養生菓子',
      kr: '도자기 허브 차 세트와 영양 다과',
    },
    default_focal_point: { x: 52, y: 48 },
    created_at: '2026-03-04T14:20:00.000Z',
    updated_at: '2026-03-04T14:20:00.000Z',
  },
  {
    id: 'media-coffee-saigon-05',
    title: 'Hạt cà phê Robusta rang mộc Sài Gòn',
    type: 'image',
    url: '/images/showcase/5.webp',
    source: 'supabase',
    width: 1600,
    height: 1066,
    mime_type: 'image/webp',
    file_size: 1350000,
    alt_i18n: {
      vi: 'Hạt cà phê Robusta rang mộc đậm vị Sài Gòn',
      en: 'Freshly roasted Saigon Robusta coffee beans',
      cn: '西贡现烘罗布斯塔咖啡豆',
      jp: '焼きたてのサイゴン・ロブスタコーヒー豆',
      kr: '신선하게 볶은 사이공 로부스타 커피 원두',
    },
    default_focal_point: { x: 50, y: 50 },
    created_at: '2026-03-05T08:00:00.000Z',
    updated_at: '2026-03-05T08:00:00.000Z',
  },
  {
    id: 'media-oria-garden-06',
    title: 'Khu vườn thảo dược Oria Farm Retreat',
    type: 'image',
    url: '/images/showcase/6.webp',
    source: 'gdrive',
    width: 2048,
    height: 1365,
    mime_type: 'image/webp',
    file_size: 2100000,
    alt_i18n: {
      vi: 'Vườn cây dược liệu xanh ngát buổi sớm',
      en: 'Lush medicinal herb garden at dawn',
      cn: '清晨郁郁葱葱的药草园',
      jp: '夜明けの青々とした薬草園',
      kr: '새벽녘의 싱그러운 약초 정원',
    },
    default_focal_point: { x: 55, y: 45 },
    created_at: '2026-03-06T07:45:00.000Z',
    updated_at: '2026-03-06T07:45:00.000Z',
  },
  {
    id: 'media-oria-video-intro-07',
    title: 'Video Giới thiệu Trải nghiệm Oria Holistic Healing',
    type: 'video',
    url: '/videos/hero-loop.mp4',
    source: 'supabase',
    width: 1920,
    height: 1080,
    mime_type: 'video/mp4',
    file_size: 18500000,
    alt_i18n: {
      vi: 'Video toàn cảnh hành trình chăm sóc sức khỏe toàn diện',
      en: 'Overview video of holistic wellness journey',
      cn: '全面健康之旅全景视频',
      jp: 'ホリスティックウェルネスの概要動画',
      kr: '홀리스틱 웰니스 여정 소개 영상',
    },
    default_focal_point: { x: 50, y: 50 },
    created_at: '2026-03-07T16:00:00.000Z',
    updated_at: '2026-03-07T16:00:00.000Z',
  },
  {
    id: 'media-oria-soundbath-08',
    title: 'Liệu pháp Chuông xoay Tây Tạng (Sound Bath)',
    type: 'image',
    url: '/images/showcase/1.webp',
    source: 'external',
    width: 1800,
    height: 1200,
    mime_type: 'image/webp',
    file_size: 1540000,
    alt_i18n: {
      vi: 'Chuông xoay kim loại trong phòng thiền định',
      en: 'Singing bowls in meditation room',
      cn: '冥想室中的颂钵',
      jp: '瞑想室のシンギングボウル',
      kr: '명상실의 싱잉볼',
    },
    default_focal_point: { x: 50, y: 50 },
    created_at: '2026-03-08T13:10:00.000Z',
    updated_at: '2026-03-08T13:10:00.000Z',
  },
];

/**
 * Mock media resolver for client-side UI preparation and inspection.
 */
export function getMockMediaAsset(mediaId: string): MediaAsset | null {
  return MOCK_MEDIA_LIBRARY.find((item) => item.id === mediaId) || null;
}
